### ISSUE TITLE
Memory Leak due to socketio

### ISSUE THREAD

**Issue by youliangtan** [open-rmf/rmf-web#614] opened 2022-06-09 02:20 UTC
## Issue Description

This mem leak issue can be seen by launching the server and dashboard. To test this, the user will need to keep the dashboard open, and then observe ram usage `api_server` by using `htop`. We can observe that the ram usage will grow over time, till the server is beyond usable due to OOM. This increment gets more severe when we switch to the "task tab" on the dashboard, along with multiple tasks showing on the page. 

![2022-05-24_21_18_47_001](https://user-images.githubusercontent.com/32189404/172745353-7697350f-77e6-4fe0-9aa7-77a3e5eb2662.png)

It is also observed that the issue happens more frequently when we have more tasks being stored in the db. Switching the db between `sqlite` and `postgres` isn't helpful.

After multiple investigations, it is found that `socketeio` is the main culprit of this memory leak issue. This issue is identified when seeing multiple "subscribe" and "unsubscribe" events performed in every update. Constantly connections and disconnection is also expensive ([ref](https://github.com/miguelgrinberg/python-socketio/issues/108#issuecomment-309066304)). This gets worst when we have more tasks or robots showing up on the dashboard. To view this behavior on chrome, go to the "developer console", select "network", then select the ws connection to the `api-server`. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/32189404/172748331-9dfe1c29-d32e-4db0-82ac-69d09eeb0a42.gif)

## Temporary fix

As a stopgap, I tried only to "subscribe" once to fleet states during init. Also, as for testing, I also removed the `socketio` component for task states. The commit is shown [here](https://github.com/open-rmf/rmf-web/commit/2f3e12f31abdc48619a5df7f1ba4cd125b6b9ffd#diff-c92fb676139d808bc5bb7ee1030ec17a2b9727825bf181bc59bfa0e70540adc1). Limiting the number of "subscribe" event greatly help to prevent the growth of the api-server mem usage. The dashboard will still work since we are also doing constant polling of http requests.

![Screenshot from 2022-06-09 09-31-18](https://user-images.githubusercontent.com/32189404/172748799-86d0ef0f-b6d4-4a6b-b31e-4b3d8b6ff434.png)

The proper way to solve this issue is to look into the implementation of [FastIO](https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/fast_io/__init__.py). The server should still work even with high frequency of subscription events.

**Comment by koonpeng** [comment] 2022-06-09 04:07
Thanks for the investigaton, I think I have a very likely cause for the leak now. The problem is probably not with socketio, rather it is with rxpy, particularly this line https://github.com/open-rmf/rmf-web/blob/b285ad33bf9ef0762099f04e9fb4742aedae1dc7/packages/api-server/api_server/routes/tasks/tasks.py#L67 leaks rxpy subscriptions.

Can you also make a PR to fix the client side always re-subscribing? As mentioned in the socketio issue, this is a wrong usage, there is no need to constantly reset the subscriptions.

**Comment by koonpeng** [comment] 2022-06-10 03:11
Fixed in #609

**Closed by koonpeng** 2022-06-10 03:11 UTC
Labels: bug
