### ISSUE TITLE
After setting "use_sim_time" to false, the robot receives a way with no waypoints

### ISSUE THREAD

**Issue by liugehaizaixue** [open-rmf/rmf-web#642] opened 2022-09-15 03:30 UTC
### Required information:

- OpenRMF installation type: 
  - Ubuntu 20.04
- OpenRMF version or commit hash
   - main
- ROS distribution and version:
  - galactic

### Description of the bug
After setting "use_sim_time" to false, the robot receives a way with no waypoints.
When using use_ sim_ time， The default time of time is 1970, so I want to use the current time to execute tasks. I set  use_sim_ time to false in launch.xml . Although the time for submitting the task is the same as the reality, my task will get stuck during the execution, and the robot will receive a path with no waypoints.Does anyone know how to solve it? Thank you

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/103879998/190307000-d398d991-3c7c-4204-93da-68720594815e.png)

The robot stopped because he received a way without waypoints

![image](https://user-images.githubusercontent.com/103879998/190307248-02c669c9-201c-4e8c-bcf4-263602269148.png)

**Comment by aaronchongth** [comment] 2022-09-19 02:38
Hello @liugehaizaixue! It looks like you are running a simulation still, and therefore will require `use_sim_time` as a flag. This is an inbuilt mechanism in ROS 2, which allows other nodes to synchronize their time with the simulated nodes which start from the epoch time, 1970s.

Perhaps this explanation will help with understanding, https://stackoverflow.com/questions/69084148/the-effect-of-use-sim-time-in-ros.

I will be closing this issue as it is not a bug.

**Closed by aaronchongth** 2022-09-19 02:38 UTC
Labels: bug
