### ISSUE TITLE
Plugin for loading batch task requests

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#472] opened 2021-08-17 11:15 UTC
Currently the dashboard has a specific `.json` format for importing batch task files. However, for each deployment the batch tasks may be available in different formats (.xlsx, .csv, .txt, etc). We could introduce a plugin system in the front end. Each deployment will have its own plugin implementation to parse the custom file format.

**Comment by koonpeng** [comment] 2021-08-18 02:54
Duplicate of #418. As mentioned in the previous issue, this is very hard to maintain and very user unfriendly. This doesn't address the issue where supporting a format is not enough to parse input files of the format, we still need to know the exact structure of the data.

The best we can do is to support input files with a certain format along with the correct data structure. Specialized scripts can be used to convert files into one of the supported format/structure.

**Closed by koonpeng** 2021-08-18 02:54 UTC
Labels: enhancement
