### ISSUE TITLE
Issue on running command lerna bootstrap

### ISSUE THREAD

**Issue by rauno99** [open-rmf/rmf-web#545] opened 2021-11-18 10:48 UTC

**Comment by rauno99** [comment] 2021-11-18 10:51
Did everything according to the instructions but react-component build fails when running command "lerna bootstrap".

> react-components@0.0.1 prepare /home/ims/dev_ws/src/covsg24_fleet_backend/rmf/rmf-web/packages/react-components
> npm run build


> react-components@0.0.1 build /home/ims/dev_ws/src/covsg24_fleet_backend/rmf/rmf-web/packages/react-components
> node scripts/build.js

lib/ant-tab.tsx:22:7 - error TS2322: Type 'FontWeight | undefined' is not assignable to type 'FontWeightProperty | PropsFunc<{}, FontWeightProperty | undefined> | undefined'.
  Type 'string & {}' is not assignable to type 'FontWeightProperty | PropsFunc<{}, FontWeightProperty | undefined> | undefined'.
    Type 'string & {}' is not assignable to type '"lighter"'.

22       fontWeight: theme.typography.fontWeightRegular,
         ~~~~~~~~~~

lib/themes/rmf-dark.tsx:22:5 - error TS2345: Argument of type '{ '@global': { '.leaflet-control-zoom a': { color: string; backgroundColor: string; }; '.leaflet-control-layers': { color: string; backgroundColor: string; }; '.leaflet-control-layers .MuiSlider-root': { ...; }; '.leaflet-control-layers .MuiInputBase-input': { ...; }; '.leaflet-pane img': { ...; }; }; }' is not assignable to parameter of type 'ThemeOptions'.
  Object literal may only specify known properties, and ''@global'' does not exist in type 'ThemeOptions'.

 22     '@global': {
        ~~~~~~~~~~~~
 23       '.leaflet-control-zoom a': {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 40       },
    ~~~~~~~~
 41     },
    ~~~~~

lib/themes/theme-provider.tsx:5:14 - error TS7053: Element implicitly has an 'any' type because expression of type '"@global"' can't be used to index type 'Theme'.
  Property '@global' does not exist on type 'Theme'.

5   '@global': theme['@global'] || {},
               ~~~~~~~~~~~~~~~~


Found 3 errors.

child_process.js:866
    throw err;
    ^

Error: Command failed: tsc --build ./tsconfig.build.json
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (/home/ims/dev_ws/src/covsg24_fleet_backend/rmf/rmf-web/packages/react-components/scripts/build.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24949,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-components@0.0.1 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-components@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ims/.npm/_logs/2021-11-18T10_45_34_950Z-debug.log
lerna info lifecycle react-components@0.0.1~prepare: Failed to exec prepare script

> rmf-auth@0.0.1 prepare /home/ims/dev_ws/src/covsg24_fleet_backend/rmf/rmf-web/packages/rmf-auth
> tsc --build && cp package.json dist/

**Comment by rauno99** [comment] 2021-11-18 11:24
npm version: 6.14.15
nvm version: 0.37.2
node version: v14.18.1
lerna version: 4.0.0
commit hash: d73bb9d746ab1ffbf57e03c112573b680d32bb4a

**Comment by ChawinTan** [comment] 2021-11-18 12:29
Not sure if this would help, but have you tried deleting all your existing node modules and then re-running `lerna bootstrap`? Also, does the error show up if you run `npm run build` in the react-components folder?

**Comment by rauno99** [comment] 2021-11-18 12:40
I removed all node modules and still have the problem. The error is still there if I run `npm run build` in the react-components folder.

**Comment by koonpeng** [comment] 2021-11-18 13:32
This is a recent bug with material ui and react, (relevant issue https://github.com/mui-org/material-ui/issues/29721). The cause is due to newer versions of `@types/react` upgraded to `csstype@3`, but `@material-ui/styles` still uses `csstype@2`.

npm should install the older version of if it sees a `package-lock.json`, maybe something else went wrong with lerna or npm which caused it to not follow `package-lock.json`. This should be fixed with #543, which includes a workaround by casting the problematic types.

**Comment by cnboonhan** [comment] 2021-11-22 07:14
i think i managed to reproduce this as well, but only if i delete / update the package-lock.json

**Comment by aaronchongth** [comment] 2022-01-10 08:02
Closing as we have shifted away from using `lerna`.

**Closed by aaronchongth** 2022-01-10 08:02 UTC
