### ISSUE TITLE
[Dashboard]: Attempting to host rmf-web on AWS EC2

### ISSUE THREAD

**Issue by MrOCW** [open-rmf/rmf-web#1005] opened 2024-08-30 10:17 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [x] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hi, I am trying to get rmf-web 0.1.0 dashboard up. I am able to access api-server via {url}:8000/docs
However, when I curl localhost:3000 in my EC2 instance after running rmf web dashboard, I am getting 404.
This is my command:
`pnpm run --filter rmf-dashboard... build && serve -s build`

However, running in development works as I am able to get a response with
`pnpm run start:react`
`curl localhost:5173`
I proceeded to configure my Load Balancer to point to 5173 and entered {url}:5173 but i get a 504 Gateway Time-out

**Comment by aaronchongth** [comment] 2024-09-02 03:16
hey there @MrOCW, unfortunately this sounds like a configuration issue on your EC2 instance. Have you tried these steps on a local machine, and not on EC2?

Sanity check, are you certain that `serve -s build` was executed? A common issue I've seen is that `serve` might not be in `PATH`, and therefore the command fails

Closing as the root cause is not related to `rmf-web`

**Closed by aaronchongth** 2024-09-02 03:16 UTC

**Comment by MrOCW** [comment] 2024-09-02 09:33
Hi @aaronchongth note that i am doing
curl localhost:3000 in my EC2 instance
and it is returning 404

serve -s build was indeed being executed

Furthermore, accessing {url} on my web browser, which points to localhost:3000 on EC2, did have some logs showing that rmf-web was being queried and returned 404

**Comment by MrOCW** [comment] 2024-09-02 10:49
I am using this docker image from minimal-rmf LOCALLY this time. I am still getting 404 when accessing localhost:3000

ARG BASE_IMAGE=docker.io/ros:jazzy-ros-base
FROM $BASE_IMAGE
ARG BRANCH=main
ARG ROS_DISTRO=jazzy

### build minimal rmf

RUN apt update && apt install -y curl

# # fetch sources
RUN mkdir -p /rmf && cd /rmf \
  && curl -sL https://github.com/open-rmf/rmf_internal_msgs/archive/refs/heads/$BRANCH.tar.gz -o rmf_internal_msgs.tar.gz \
  && curl -sL https://github.com/open-rmf/rmf_building_map_msgs/archive/refs/heads/$BRANCH.tar.gz -o rmf_building_map_msgs.tar.gz \
  && mkdir -p /rmf/src/rmf/rmf_internal_msgs && tar zxf rmf_internal_msgs.tar.gz -C /rmf/src/rmf/rmf_internal_msgs --strip-components=1 && rm rmf_internal_msgs.tar.gz \
  && mkdir -p /rmf/src/rmf/rmf_building_map_msgs && tar zxf rmf_building_map_msgs.tar.gz -C /rmf/src/rmf/rmf_building_map_msgs --strip-components=1 && rm rmf_building_map_msgs.tar.gz

RUN rosdep update && rosdep install --from-paths /rmf/src -yi

RUN cd /rmf \
  && . /opt/ros/$ROS_DISTRO/setup.sh \
  && colcon build --merge-install --install-base /opt/rmf --cmake-args -DCMAKE_BUILD_TYPE=Release \
  && rm -rf /rmf

# install tools for rmf-web

RUN curl -fsSL https://get.pnpm.io/install.sh | bash -
# shell runs in non-interactive mode, which does not source .bashrc so we need to set the PATH manually
ENV PNPM_HOME /root/.local/share/pnpm
ENV PATH "$PNPM_HOME:$PATH"

# nodejs seems to have changed the official mirror, the default in pnpm is very slow now
RUN pnpm config -g set 'node-mirror:release' https://nodejs.org/dist && pnpm env use --global lts

RUN apt update && apt install -y python3-venv


docker run -it --name="rmf-web" --net=host --ipc=host --privileged --volume..... rmf-web-jazzy

proceeded to follow the instructions on the README and serve dashboard

**Comment by aaronchongth** [comment] 2024-09-03 01:19
The images are passed from the API server to the dashboard via REST, so if your building is extremely large and the map sizes are very large, dips in performance is expected

especially since you are accessing the browser through your own machine, large transports will be affected. I would suggest reducing the quality of your maps. Overall the maps should start loading faster after you have done it once for every floor, your browser will help with the caching.

**Comment by MrOCW** [comment] 2024-09-03 02:18
my L1 and L2 is loading fine after a while, however, the rest of my floors never loads unfortunately.
In the previous version of 22.09 which we brought to production, all floors and infra were loaded.

**Comment by aaronchongth** [comment] 2024-09-03 02:43
Can you verify that it doesn't work locally (not on EC2), using the docker images?
you can check the dev console of your browser to see if any errors occurred, with debug logs

> In the api-server, i see that the files are loaded to run/cache

this makes me suspect it is still a size or bandwidth issue
sanity check, if the floors do not load, what about the doors or lifts on those floors? Do they get rendered?

**Comment by aaronchongth** [comment] 2024-09-03 03:00
Just a few checks, any chance you could share the building map file, along with all the floor plans? So if it is an upstream issue we can investigate it further?

A minor check would also be to share the file sizes of the floor plans, for example the sizes for L1 and L2 (since they load fine for you), vs the other floors

> sanity check, if the floors do not load, what about the doors or lifts on those floors? Do they get rendered?

the reason i asked this, is to check if the level is indeed situated correctly, or was it set up with large offsets and is somewhere else in the map and requires much zooming and panning.

**Comment by MrOCW** [comment] 2024-09-03 04:08
> Can you verify that it doesn't work locally (not on EC2), using the docker images?

Yes same issue locally, L1 L2 loads, L3 onwards does not load

> what about the doors or lifts on those floors

Not sure how this main version should look like but the entrances to the lifts, and the turnstiles are shown in green

> this makes me suspect it is still a size or bandwidth issue

Possibly, but shouldnt this make the other floors still load albeit slower?

> share the file sizes of the floor plans

L1: 3.1MB
L2: 2.4MB
L3: 1.3MB
L5: 14.1MB
L6: 1.1MB
....
theres too many floors to share but they range from 1~14MB

> do the other floors have walls drawn in their building map level

is this from traffic-editor?

**Comment by MrOCW** [comment] 2024-09-03 04:10
![image](https://github.com/user-attachments/assets/b930bbb6-c46c-465c-b78d-798a42ad7920)

Note that lift adapter is not up

**Comment by aaronchongth** [comment] 2024-09-03 04:35
This looks normal

> is this from traffic-editor?

yes, please review each floor in traffic-editor that there are walls drawn into the levels, according to the floorplan
this generates walls in simulation if you're using `building_map_tools`, but also help `rmf-web` figure out what size the scene boundary should be

**Comment by MrOCW** [comment] 2024-09-03 06:25
> Could you also check if there are any errors in the browser console log

![image](https://github.com/user-attachments/assets/85e3b5da-83a2-45f9-80af-0edb9e30119f)
Upon L1 and L2 loading, the console starts spamming this:
![image](https://github.com/user-attachments/assets/0818db34-dddf-4a80-a859-4ec4f05f28f0)




> yes, please review each floor in traffic-editor that there are walls drawn into the levels

seems like no walls were drawn on ALL floors. This would mean that L1 and L2 are not supposed to render properly as well?

**Comment by MrOCW** [comment] 2024-09-03 07:01
adding the walls fixed it! the floors with walls are now loading correctly thank you!
might be worth adding this into documentation
by the way, what kind of resolution would you recommend for the floorplans?

**Comment by aaronchongth** [comment] 2024-09-03 07:30
good to hear that.

> might be worth adding this into documentation

Good point, https://github.com/open-rmf/rmf-web/pull/1006

> by the way, what kind of resolution would you recommend for the floorplans?

This is a tough question to answer, for the best performance, smaller resolutions are always better, as it will help with network transport, as well as loading in `react-three-fiber` overall. For folks with an amazing network (running everything locally for example), and users with powerful machines to view the dashboard, they can go as high resolution as they want. However if the dashboard has to work through rough networks, and the users are using relatively under-powered machines, the resolution will have to be reduced.

I would recommend to reduce resolution to the point where the artifacts desired (by the users) in the floorplans are at least still visible and sharp-ish.

We have plans to further optimize how we are rendering our maps, but how much more performance we can squeeze out is unknown at this point of time.
