### ISSUE TITLE
facing issue and error when pull rmf-web and run 

### ISSUE THREAD

**Issue by KyawMyoThu** [open-rmf/rmf-web#594] opened 2022-03-17 06:21 UTC
I followed steps in rmf-web git instructions and run rmf-web, it can not successfully run and showing errors as shown in screenshot.

I'd already setup and installed ROS2 & rmf also.

Could you please help to give some guidelines how to troubleshoot step by step to resolve it and moving forward properly ASAP.

![image](https://user-images.githubusercontent.com/25733022/158748641-5272c6e6-1a2a-44b5-9d25-ab96bdabc812.png)

![image](https://user-images.githubusercontent.com/25733022/158748786-89aa3237-831d-489e-af59-c68cdc1380a4.png)

**Comment by cnboonhan** [comment] 2022-03-17 08:58
hi, it seems like the tortoise python dependency is not available, did you run the bootstrap scripts here? https://github.com/open-rmf/rmf-web#bootstrap

I tried a clean build without running these bootstrap scripts, and I got a similar error as you, so that seems to most likely cause. 

If some further errors appear, would be good to run `npm run build` in the `packages/dashboard` workspace to see if that is a fix.

**Comment by KyawMyoThu** [comment] 2022-03-17 09:50
Hi cnboonhan,

Thanks for your reply and comment.

Yes, sure.. I'd definitely run those bootstraps one after another and testing, 
but still same errors come out.

run option: 1) 
![image](https://user-images.githubusercontent.com/25733022/158782212-f15636a8-02c6-4bc1-9231-eb715a2dded9.png)

then build and npm start. => got same error.

run Option: 2
![image](https://user-images.githubusercontent.com/25733022/158782649-a931d64f-b91e-40cc-ab23-c42147640dd6.png)

then build and npm start. => got same error.

![image](https://user-images.githubusercontent.com/25733022/158782835-657af5ad-7ae3-484a-b6ce-8aaa8cecc70e.png)

**Comment by cnboonhan** [comment] 2022-03-18 01:51
yes, reproducing will be key here: there could be multiple root causes.  The core issue is that the npm command that breaks starts up a pipenv environment, which requires the tortoise python dependency. Somehow, this dependency was not installed within the pipenv environment.

**Comment by KyawMyoThu** [comment] 2022-03-18 05:48
## Bug report

### Required information:

- Operating system and version:
=> Ubuntu 20.04

- OpenRMF installation type:
=> I setup from here step by step.
=> https://github.com/open-rmf/rmf

- ROS distribution and version:
=>  I followed this below link steps and installed ROS
=> https://docs.ros.org/en/galactic/Installation/Ubuntu-Install-Debians.html

- ROS installation type:
=>  - Ubuntu 20.04

### Description of the bug



### Steps to reproduce the bug

=> after above installation and setting up steps are finished, then RMF can start up 
![image](https://user-images.githubusercontent.com/25733022/158943925-c7c9dfba-128c-4e14-bf25-ab11e28edf55.png)

=> for RMF-Web, I followed the steps from below link, but got start up error coming out.
https://github.com/open-rmf/rmf-web

=> Facing this issue, and got this error, rmf-web cannot start up successfully.
![image](https://user-images.githubusercontent.com/25733022/158944288-6feaa54e-9efa-432d-8cd2-0842a97d367f.png)

=> then RMF-Web is just coming out like that.
![image](https://user-images.githubusercontent.com/25733022/158944818-af95fd5c-d471-4d43-bd26-a0feb8dee7f3.png)


Could you please kindly give some hint to test it out and try, how to troubleshoot those issues to be resolved ASAP.
Thanks.

**Comment by KyawMyoThu** [comment] 2022-03-21 04:30
> yes, reproducing will be key here: there could be multiple root causes. The core issue is that the npm command that breaks starts up a pipenv environment, which requires the tortoise python dependency. Somehow, this dependency was not installed within the pipenv environment.

Which packages do I have to install, reinstall, any steps for hints in those kind of situation to resolve it?

**Comment by aaronchongth** [comment] 2022-03-21 10:49
There are two issues here,

> Facing this issue, and got this error, rmf-web cannot start up successfully.

I think I know what is going on now, you already have a simulation instance running, `airport_terminal`, before you called `npm run start`. One thing to note, is that `npm run start` [spins up a headless simulation instance as well](https://github.com/open-rmf/rmf-web/blob/main/packages/dashboard/package.json#L7), therefore you get the error mentioned.

As for the robots not registering on the dashboard , this is due to the default `server_uri` is not targeting the `api-server`. I apologize for missing out on this piece of documentation during our migration. This is being patched in now.

Try this in the meantime,

```bash
ros2 launch rmf_demos_gz airport_terminal.launch.xml server_uri:="w://localhost:8001"
```

For `rmf-web`, checkout to this https://github.com/open-rmf/rmf-web/pull/595, the default start script on this branch does on launch any headless simulation instances,

```bash
cd packages/dashboard
npm start
```

**Comment by daichuihua** [comment] 2022-03-23 03:50
> > yes, reproducing will be key here: there could be multiple root causes. The core issue is that the npm command that breaks starts up a pipenv environment, which requires the tortoise python dependency. Somehow, this dependency was not installed within the pipenv environment.
> 
> Which packages do I have to install, reinstall, any steps for hints in those kind of situation to resolve it?

i  also face the same problem and don't know how to solve it

**Comment by mayman99** [comment] 2022-03-23 09:40
As of right now, first for the dashboard, you need to run **`npm run start:react`** NOT `npm start`, and in separate terminal, navigate to the **`api-server`** package, and run **`npm run start`.**

This will ensure it will work as expected, if you've already run the bootstrap scrip, and built the dashboard, and provided the server-uri param to the ros2 launch file e.g. **`server_uri:="ws://localhost:8001"`**

We are patching the startup scripts to make it simpler atm.

**Comment by aaronchongth** [comment] 2022-03-25 07:46
Closing via https://github.com/open-rmf/rmf-web/pull/595 and https://github.com/open-rmf/rmf_demos/pull/130.

**Closed by aaronchongth** 2022-03-25 07:46 UTC
Labels: bug

**Comment by mayman99** [comment] 2022-04-12 03:01
@daichuihua replied on the other issue :)

**Comment by mayman99** [comment] 2022-04-12 03:04
> As of right now, first for the dashboard, you need to run `npm run start:react` not `npm start`, and in separate terminal, navigate to the api-server package, and run `npm run start`.

For ref purposes, just `npm run start` in  the dashboard package works, running two separate commands is not anymore needed.

**Comment by daichuihua** [comment] 2022-04-12 06:11
> > As of right now, first for the dashboard, you need to run `npm run start:react` not `npm start`, and in separate terminal, navigate to the api-server package, and run `npm run start`.
> 
> For ref purposes, just `npm run start` in the dashboard package works, running two separate commands is not anymore needed.

1>cd rmf-web-main && cd scripts && ./bootstrap.sh (1st terminal)
![Screenshot from 2022-04-12 14-02-59](https://user-images.githubusercontent.com/30583933/162892410-7cb86e95-7af7-49ed-b46f-29c3af62452a.png)

2>ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:8001" (2nt terminal)
![Screenshot from 2022-04-12 14-04-37](https://user-images.githubusercontent.com/30583933/162892444-46c77e90-17cf-4ab8-a24e-846222cab9ee.png)

3>cd rmf-web-main/packages/dashboard  && npm run start (3rd terminal)
![Screenshot from 2022-04-12 14-07-07](https://user-images.githubusercontent.com/30583933/162892505-28f59267-9c8b-4edb-a1ce-3b7f8ee59e9e.png)
![Screenshot from 2022-04-12 14-07-45](https://user-images.githubusercontent.com/30583933/162892516-94cf0853-7ea9-4067-b390-28af948c5171.png)


result:
[start:rmf-server]     from tortoise import Tortoise
[start:rmf-server] ModuleNotFoundError: No module named 'tortoise'
[start:rmf-server] npm ERR! Lifecycle script `start:rmf-server` failed with error: 
[start:rmf-server] npm ERR! Error: command failed 
[start:rmf-server] npm ERR!   in workspace: rmf-dashboard@0.0.1 
[start:rmf-server] npm ERR!   at location: /home/dch/rmf-web-main/packages/dashboard 
[start:rmf-server] npm run start:rmf-server exited with code 1
[start:react] Compiled successfully!
[start:react] 
[start:react] You can now view rmf-dashboard in the browser.
[start:react] 
[start:react]   Local:            http://localhost:3000
[start:react]   On Your Network:  http://10.10.17.90:3000
[start:react] 
[start:react] Note that the development build is not optimized.
[start:react] To create a production build, use npm run build.
