### ISSUE TITLE
[Bug]: ASGI Application Exception Causing Task Endpoint Inconsistencies After Prolonged Operation in RMF

### ISSUE THREAD

**Issue by osama-z-salah** [open-rmf/rmf-web#1021] opened 2024-10-29 01:35 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04.4 LTS

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

rmf_web 0.1.0

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

I'm encountering an error while conducting reliability tests on a real robot with RMF. The error occurs after several hours of testing, and the task endpoint starts incorrectly reporting that there are no running or queued tasks, even though the tasks were successfully sent. Eventually, the dispatcher starts rejecting new tasks.  I'm running a simple script that continuously queries the task endpoint to ensure that there is always one running task and two in the queue. After a few hours of continuous operation, I receive the error above. After the error, the task endpoint incorrectly reports 0 running and 0 queued tasks, although the task submission was previously successful. This leads to the system continuously trying to queue new tasks, causing the dispatcher to eventually start rejecting them. Below is the stack trace from the ASGI application:
```
[start:rmf-server] Exception in ASGI application
[start:rmf-server] Traceback (most recent call last):
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
[start:rmf-server]     result = await app(  # type: ignore[func-returns-value]
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
[start:rmf-server]     return await self.app(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
[start:rmf-server]     await super().__call__(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
[start:rmf-server]     await self.middleware_stack(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
[start:rmf-server]     raise exc
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
[start:rmf-server]     await self.app(scope, receive, _send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
[start:rmf-server]     await self.simple_response(scope, receive, send, request_headers=headers)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
[start:rmf-server]     await self.app(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
[start:rmf-server]     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[start:rmf-server]     raise exc
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[start:rmf-server]     await app(scope, receive, sender)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
[start:rmf-server]     await self.middleware_stack(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
[start:rmf-server]     await route.handle(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
[start:rmf-server]     await self.app(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
[start:rmf-server]     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
[start:rmf-server]     raise exc
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
[start:rmf-server]     await app(scope, receive, sender)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
[start:rmf-server]     response = await func(request)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 285, in app
[start:rmf-server]     raise e
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 275, in app
[start:rmf-server]     solved_result = await solve_dependencies(
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 600, in solve_dependencies
[start:rmf-server]     solved = await run_in_threadpool(call, **sub_values)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
[start:rmf-server]     return await anyio.to_thread.run_sync(func, *args)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
[start:rmf-server]     return await get_async_backend().run_sync_in_worker_thread(
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
[start:rmf-server]     return await future
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
[start:rmf-server]     result = context.run(func, *args)
[start:rmf-server]   File "/home/nanofleet/rmf-web-0.1.0/packages/api-server/api_server/dependencies.py", line 57, in dep
[start:rmf-server]     datetime.fromtimestamp(int(parts[1]) / 1000, timezone.utc),
[start:rmf-server] ValueError: year 287396 is out of range
```

### Steps to reproduce the bug

1- Set up RMF with a simple robot fleet.
2- Run a script that continuously queries the task endpoint and submits tasks.
3- After several hours, observe that the task endpoint reports 0 running and 0 queued tasks incorrectly.
4- The error leads to the task dispatcher rejecting new tasks when a lot of task has been sent.

**Comment by aaronchongth** [comment] 2024-10-29 11:00
Please use a code block for multi-line logs, https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

```
like
this
```

Please also add the logs from the task dispatcher as well.

Are you able to share the script that you are using for testing, so we can attempt to reproduce it? Because the error does not appear to be an error with the dispatcher or `rmf-web`, rather it looks like it is related to how the tasks were being  was constructed, if the start time . For some context the line that your logs are pointing to is the `time_between_query` dependency when querying for tasks, and that is trying to parse the timestamps from the query. So if your script is producing invalid start times for task requests, it will get rejected by the task dispatcher, and it will also show up as an invalid range on the API server logs as mentioned here.

It would be useful to also know the list of tasks that are sent out to the API server, and the particular task request (the entire json) that caused this error to start

**Comment by osama-z-salah** [comment] 2024-11-01 02:17
Hi @aaronchongth ,

Thanks for your response. I wanted to share the script I'm currently using for testing:

```
import requests
import time
import json
from datetime import datetime

# Constants for API Endpoints
TASK_URL = "http://192.168.1.11:8000/tasks/dispatch_task"
STATUS_URL = "http://192.168.1.11:8000/tasks"

# Define the robot and fleet we are focusing on
TARGET_ROBOT = "nano500xw02"
TARGET_FLEET = "Robot500xw"

def generate_task_payload():
    current_time = int(time.time() * 1000)  # Current time in milliseconds
    payload = {
        "type": "dispatch_task_request",
        "request": {
            "unix_millis_earliest_start_time": current_time,
            "unix_millis_request_time": current_time,
            "priority": {
                "type": "binary",
                "value": 0
            },
            "category": "compose",
            "description": {
                "category": "transfer_material",
                "phases": [
                    {
                        "activity": {
                            "category": "sequence",
                            "description": {
                                "activities": [
                                    {
                                        "category": "go_to_place",
                                        "description": "station_500"
                                    },
                                    {
                                        "category": "go_to_place",
                                        "description": "unloading_station"
                                    },
                                    
                                    {
                                        "category": "perform_action",
                                        "description": {
                                            "unix_millis_action_duration_estimate": 10000,
                                            "category": "pigeonhole_handling",
                                            "description": {
                                                "target_task": "unloading",
                                                "length": "1.06",
                                                "width": "0.84"
                                            },
                                            "use_tool_sink": False
                                        }
                                    }
                                ]
                            }
                        }
                    }
                ]
            },
            "labels": [""],
            "requester": "rmf_demos_tasks",
            "fleet_name": TARGET_FLEET
        }
    }
    return payload

def send_task():
    task_payload = generate_task_payload()
    # Log the payload before sending
    print(f"Sending task payload: {json.dumps(task_payload, indent=2)}")

    response = requests.post(TASK_URL, json=task_payload)
    if response.status_code == 200:
        print("Task submitted successfully")
    else:
        print(f"Failed to submit task: {response.status_code} - {response.text}")

def get_tasks_status():
    response = requests.get(STATUS_URL, headers={"accept": "application/json"})
    if response.status_code == 200:
        tasks = response.json()

        # Filter tasks for the target robot and fleet
        filtered_tasks = [
            task for task in tasks
            if isinstance(task.get('assigned_to'), dict)  # Ensure assigned_to is a dictionary
            and task['assigned_to'].get('name') == TARGET_ROBOT
            and task['assigned_to'].get('group') == TARGET_FLEET
        ]

        return filtered_tasks
    else:
        print(f"Failed to retrieve tasks: {response.status_code} - {response.text}")
        return []

def manage_tasks():
    while True:
        tasks = get_tasks_status()
        running_tasks = [task for task in tasks if task.get('status') == 'underway']
        queued_tasks = [task for task in tasks if task.get('status') == 'queued']
        
        print(f"Running tasks for {TARGET_ROBOT}: {len(running_tasks)}, Queued tasks: {len(queued_tasks)}")

        # Ensure only 1 task is running
        if len(running_tasks) == 0 and len(queued_tasks) <= 1:
            send_task()
            print("Starting the next queued task...")

        # Sleep for 5 seconds before the next status check
        time.sleep(120)

if __name__ == "__main__":
    manage_tasks()
```
There isn't a specific task request causing the issue—it's consistently the same request. The script runs as expected for a few hours, but then the get_tasks_status() function stops working correctly and consistently reports that no tasks are queued or running. As a result, the send_task() function continues sending tasks, which are subsequently rejected by the task dispatcher. In the RMF server, I also receive error messages related to this.

**Comment by aaronchongth** [comment] 2024-11-01 03:45
> It would be useful to also know the list of tasks that are sent out to the API server, and the particular task request (the entire json) that caused this error to start

Please provide this.

Thanks for providing the script, I have a few follow-up questions,
* are you running the API server with sim time (depending on the server config file, it is default true if a simple `pnpm start` is invoked)?
* What about the task dispatcher (`use_sim_time:=1`)?
* Are you running a simulation that is completing the tasks?

My first intuition is that there is a mismatch between the different component's time, perhaps one of them running in sim time, while another is running in real time. This could cause an overflow

**Comment by osama-z-salah** [comment] 2024-11-04 08:49
Hi @aaronchongth,

Thanks for your follow-up and suggestions.

I've investigated further and realized that this issue is happening specifically after charging tasks are initiated. The problem appears to be that, once the charging tasks are completed by the fleet adapter, they seem to become "standby" and are never marked as completed in the RMF server.  The fleet adapter believes the robot has completed charging and resumes the task, but the RMF server doesn't update the task status accordingly.

At this point, the /tasks endpoint stops reporting task statuses altogether, which leads my script to continue submitting new tasks since it incorrectly believes there are no running or queued tasks. Eventually, this overwhelms the dispatcher, leading to task rejections and the "year out of range" error I mentioned previously.
```
[rmf_task_dispatcher-14] [INFO] [1730709992.790626720] [rmf_task_dispatcher]:  - Start new bidding task: compose.dispatch-341
[rmf_task_dispatcher-14] [INFO] [1730709994.565049720] [rmf_task_dispatcher]: Add Task [compose.dispatch-343] to a bidding queue
[rmf_task_dispatcher-14] [INFO] [1730709994.990646009] [rmf_task_dispatcher]: Task auction for [compose.dispatch-341] did not receive any bids
[rmf_task_dispatcher-14] [WARN] [1730709994.990713525] [rmf_task_dispatcher]: Dispatcher Bidding Result: task [compose.dispatch-341] has no submissions during bidding. Dispatching failed, and the task will not be performed.
```

It seems like there is some issue in how the task state transitions are being handled for charging tasks—perhaps the RMF server isn't being properly updated by the fleet adapter, or there is a mismatch in the task completion signaling.

**Comment by aaronchongth** [comment] 2024-11-04 10:38
Thanks for looking further into it @osama-z-salah! For more context, the API server does not update any task statuses on its own. It only ever receives updates over websockets from the fleet adapter and task dispatcher (if configured) and stores it accordingly into the database based on the task ID. So any missing updates to "complete" the charging task is going to have to be published from the fleet adapters.

That being said, semantically a charging task is never "complete" unless the robot is charged till 100%, and based on the configuration of the fleet adapter, the fleet adapter is also allowed to accept new tasks and send charging robots to perform new tasks, ignoring that they are currently charging. I haven't looked into it yet, but we could potentially cancel  a charging task if ever it is interrupted by a new task, this will need to be implemented in https://github.com/open-rmf/rmf_ros2, and the task state updated to `canceled` according to https://github.com/open-rmf/rmf_api_msgs/blob/main/rmf_api_msgs/schemas/task_state.json#L189. PRs are welcome!

Another way to go about it, would be to modify your custom testing script to accommodate this behavior.

> Additionally, regarding the use_sim_time setting, I found that it was incorrectly set to true despite setting the environment variable RMF_SERVER_USE_SIM_TIME to false.

You can set it from the config too, https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/sqlite_local_config.py#L12. Make sure that your server config file does not have that line `use_sim_time:=true`, as it overwrites the environment variable `RMF_SERVER_USE_SIM_TIME`. The environment variable is only useful when your server config file does not already define the ros arg, because they will just be appended to each other.

I'll be closing this ticket now, since it is not a bug related to `rmf-web`, and the behavior you are seeking will need to be implemented elsewhere

**Closed by aaronchongth** 2024-11-04 10:38 UTC
Labels: bug
