### ISSUE TITLE
[Bug]: Swagger UI API docs not loading

### ISSUE THREAD

**Issue by shannenlolol** [open-rmf/rmf-web#821] opened 2023-10-31 01:41 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Rolling

### ROS installation type

Source build

### Description of the bug

The Swagger UI link provided for the API docs (https://open-rmf.github.io/rmf-web/docs/api-server/ ) is not working and shows a blank screen. It was working fine a few months back when I last checked.

### Steps to reproduce the bug

View the link at https://open-rmf.github.io/rmf-web/docs/api-server/

**Comment by aaronchongth** [comment] 2023-11-01 19:59
Thanks for flagging this! We believe https://github.com/open-rmf/rmf-web/pull/786 is the root cause, will look into it.

In the meantime, you can access the API once you start the `api-server` following the instructions, and navigating to `localhost:8000/docs`

**Comment by aaronchongth** [comment] 2024-02-28 08:42
Fixed with https://github.com/open-rmf/rmf-web/pull/907

**Closed by aaronchongth** 2024-02-28 08:42 UTC
Labels: bug
